apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  type: ClusterIP
  selector:
    app: techtrends
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }} 
      targetPort: 3111