namespace:
  name: prod
 
service:
  port: 7111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: trapthyshetty/techtrends 
  tag: latest
  pullPolicy: Always

replicaCount: 5

resources:
  requests:
    cpu: 350m
    memory: 120Mi
  limits:
    cpu: 500m
    memory: 256Mi

containerport: 3111

livenessProbe:
  path: /healthz
  
readinessProbe:
  path: /healthz